
name: Daily Yahoo Scrape

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scrape script
        run: python scrape_all_asx.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/*.json
          git commit -m "Daily scrape $(date '+%Y-%m-%d')" || echo "No changes"
          git push origin HEAD
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

